# Generated by Django 2.0.7 on 2018-09-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table=None,
        ),
    ]
