# Generated by Django 2.0.7 on 2018-09-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('pH', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Type')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Variety')),
            ],
        ),
    ]
